In [3]:
import tweepy
#from twitter_authentication import bearer_token
import time
import pandas as pd

In [50]:
consumer_key = ' '
consumer_secret = ' '
access_token= ' '
access_token_secret = ' '
bearer_token = ' '

In [53]:

hours = ['00','01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23']
days = ['29','28','27','26','25','24']
for day in days:
    for hour in hours:    
        end_time='2022-4-'+day+'T'+hour+':00:00Z'
        print(end_time)
        #print(day[page])

2022-4-29T00:00:00Z
2022-4-29T01:00:00Z
2022-4-29T02:00:00Z
2022-4-29T03:00:00Z
2022-4-29T04:00:00Z
2022-4-29T05:00:00Z
2022-4-29T06:00:00Z
2022-4-29T07:00:00Z
2022-4-29T08:00:00Z
2022-4-29T09:00:00Z
2022-4-29T10:00:00Z
2022-4-29T11:00:00Z
2022-4-29T12:00:00Z
2022-4-29T13:00:00Z
2022-4-29T14:00:00Z
2022-4-29T15:00:00Z
2022-4-29T16:00:00Z
2022-4-29T17:00:00Z
2022-4-29T18:00:00Z
2022-4-29T19:00:00Z
2022-4-29T20:00:00Z
2022-4-29T21:00:00Z
2022-4-29T22:00:00Z
2022-4-29T23:00:00Z
2022-4-29T24:00:00Z
2022-4-28T00:00:00Z
2022-4-28T01:00:00Z
2022-4-28T02:00:00Z
2022-4-28T03:00:00Z
2022-4-28T04:00:00Z
2022-4-28T05:00:00Z
2022-4-28T06:00:00Z
2022-4-28T07:00:00Z
2022-4-28T08:00:00Z
2022-4-28T09:00:00Z
2022-4-28T10:00:00Z
2022-4-28T11:00:00Z
2022-4-28T12:00:00Z
2022-4-28T13:00:00Z
2022-4-28T14:00:00Z
2022-4-28T15:00:00Z
2022-4-28T16:00:00Z
2022-4-28T17:00:00Z
2022-4-28T18:00:00Z
2022-4-28T19:00:00Z
2022-4-28T20:00:00Z
2022-4-28T21:00:00Z
2022-4-28T22:00:00Z
2022-4-28T23:00:00Z
2022-4-28T24:00:00Z
2022-4-27T00:00:00Z
2022-4-27T01:00:00Z
2022-4-27T02:00:00Z
2022-4-27T03:00:00Z
2022-4-27T04:00:00Z
2022-4-27T05:00:00Z
2022-4-27T06:00:00Z
2022-4-27T07:00:00Z
2022-4-27T08:00:00Z
2022-4-27T09:00:00Z
2022-4-27T10:00:00Z
2022-4-27T11:00:00Z
2022-4-27T12:00:00Z
2022-4-27T13:00:00Z
2022-4-27T14:00:00Z
2022-4-27T15:00:00Z
2022-4-27T16:00:00Z
2022-4-27T17:00:00Z
2022-4-27T18:00:00Z
2022-4-27T19:00:00Z
2022-4-27T20:00:00Z
2022-4-27T21:00:00Z
2022-4-27T22:00:00Z
2022-4-27T23:00:00Z
2022-4-27T24:00:00Z
2022-4-26T00:00:00Z
2022-4-26T01:00:00Z
2022-4-26T02:00:00Z
2022-4-26T03:00:00Z
2022-4-26T04:00:00Z
2022-4-26T05:00:00Z
2022-4-26T06:00:00Z
2022-4-26T07:00:00Z
2022-4-26T08:00:00Z
2022-4-26T09:00:00Z
2022-4-26T10:00:00Z
2022-4-26T11:00:00Z
2022-4-26T12:00:00Z
2022-4-26T13:00:00Z
2022-4-26T14:00:00Z
2022-4-26T15:00:00Z
2022-4-26T16:00:00Z
2022-4-26T17:00:00Z
2022-4-26T18:00:00Z
2022-4-26T19:00:00Z
2022-4-26T20:00:00Z
2022-4-26T21:00:00Z
2022-4-26T22:00:00Z
2022-4-26T23:00:00Z
2022-4-26T24:00:00Z
2022-4-25T00:00:00Z
2022-4-25T01:00:00Z
2022-4-25T02:00:00Z
2022-4-25T03:00:00Z
2022-4-25T04:00:00Z
2022-4-25T05:00:00Z
2022-4-25T06:00:00Z
2022-4-25T07:00:00Z
2022-4-25T08:00:00Z
2022-4-25T09:00:00Z
2022-4-25T10:00:00Z
2022-4-25T11:00:00Z
2022-4-25T12:00:00Z
2022-4-25T13:00:00Z
2022-4-25T14:00:00Z
2022-4-25T15:00:00Z
2022-4-25T16:00:00Z
2022-4-25T17:00:00Z
2022-4-25T18:00:00Z
2022-4-25T19:00:00Z
2022-4-25T20:00:00Z
2022-4-25T21:00:00Z
2022-4-25T22:00:00Z
2022-4-25T23:00:00Z
2022-4-25T24:00:00Z
2022-4-24T00:00:00Z
2022-4-24T01:00:00Z
2022-4-24T02:00:00Z
2022-4-24T03:00:00Z
2022-4-24T04:00:00Z
2022-4-24T05:00:00Z
2022-4-24T06:00:00Z
2022-4-24T07:00:00Z
2022-4-24T08:00:00Z
2022-4-24T09:00:00Z
2022-4-24T10:00:00Z
2022-4-24T11:00:00Z
2022-4-24T12:00:00Z
2022-4-24T13:00:00Z
2022-4-24T14:00:00Z
2022-4-24T15:00:00Z
2022-4-24T16:00:00Z
2022-4-24T17:00:00Z
2022-4-24T18:00:00Z
2022-4-24T19:00:00Z
2022-4-24T20:00:00Z
2022-4-24T21:00:00Z
2022-4-24T22:00:00Z
2022-4-24T23:00:00Z
2022-4-24T24:00:00Z

In [60]:
tweets_array = []
hours = ['01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23']
days = ['29','28','27','26','25','24']
#hours = ['00','01']
#days = ['29']
for day in days:
    for hour in hours: 
        client = tweepy.Client(bearer_token, wait_on_rate_limit=True)
        query = 'elon musk twitter -is:retweet lang:en'
        end_time = '2022-4-'+day+'T'+hour+':00:00Z'
        response = client.search_recent_tweets(query=query,
                                               user_fields = ['username', 'public_metrics', 'description', 'location'],
                                               tweet_fields = ['created_at', 'geo', 'public_metrics', 'text'],
                                               expansions = 'author_id',
                                               end_time=end_time,
                                               max_results=100)
        time.sleep(1)
        tweets_array.append(response)
        print(end_time)



tweets_array[0].data[0]
tweets_array[0].includes['users'][2]
tweets_array[0].includes['users'][2].description

2022-4-29T01:00:00Z
2022-4-29T02:00:00Z
2022-4-29T03:00:00Z
2022-4-29T04:00:00Z
2022-4-29T05:00:00Z
2022-4-29T06:00:00Z
2022-4-29T07:00:00Z
2022-4-29T08:00:00Z
2022-4-29T09:00:00Z
2022-4-29T10:00:00Z
2022-4-29T11:00:00Z
2022-4-29T12:00:00Z
2022-4-29T13:00:00Z
2022-4-29T14:00:00Z
2022-4-29T15:00:00Z
2022-4-29T16:00:00Z
2022-4-29T17:00:00Z
2022-4-29T18:00:00Z
2022-4-29T19:00:00Z
2022-4-29T20:00:00Z
2022-4-29T21:00:00Z
2022-4-29T22:00:00Z
2022-4-29T23:00:00Z
2022-4-28T01:00:00Z
2022-4-28T02:00:00Z
2022-4-28T03:00:00Z
2022-4-28T04:00:00Z
2022-4-28T05:00:00Z
2022-4-28T06:00:00Z
2022-4-28T07:00:00Z
2022-4-28T08:00:00Z
2022-4-28T09:00:00Z
2022-4-28T10:00:00Z
2022-4-28T11:00:00Z
2022-4-28T12:00:00Z
2022-4-28T13:00:00Z
2022-4-28T14:00:00Z
2022-4-28T15:00:00Z
2022-4-28T16:00:00Z
2022-4-28T17:00:00Z
2022-4-28T18:00:00Z
2022-4-28T19:00:00Z
2022-4-28T20:00:00Z
2022-4-28T21:00:00Z
2022-4-28T22:00:00Z
2022-4-28T23:00:00Z
2022-4-27T01:00:00Z
2022-4-27T02:00:00Z
2022-4-27T03:00:00Z
2022-4-27T04:00:00Z
2022-4-27T05:00:00Z
2022-4-27T06:00:00Z
2022-4-27T07:00:00Z
2022-4-27T08:00:00Z
2022-4-27T09:00:00Z
2022-4-27T10:00:00Z
2022-4-27T11:00:00Z
2022-4-27T12:00:00Z
2022-4-27T13:00:00Z
2022-4-27T14:00:00Z
2022-4-27T15:00:00Z
2022-4-27T16:00:00Z
2022-4-27T17:00:00Z
2022-4-27T18:00:00Z
2022-4-27T19:00:00Z
2022-4-27T20:00:00Z
2022-4-27T21:00:00Z
2022-4-27T22:00:00Z
2022-4-27T23:00:00Z
2022-4-26T01:00:00Z
2022-4-26T02:00:00Z
2022-4-26T03:00:00Z
2022-4-26T04:00:00Z
2022-4-26T05:00:00Z
2022-4-26T06:00:00Z
2022-4-26T07:00:00Z
2022-4-26T08:00:00Z
2022-4-26T09:00:00Z
2022-4-26T10:00:00Z
2022-4-26T11:00:00Z
2022-4-26T12:00:00Z
2022-4-26T13:00:00Z
2022-4-26T14:00:00Z
2022-4-26T15:00:00Z
2022-4-26T16:00:00Z
2022-4-26T17:00:00Z
2022-4-26T18:00:00Z
2022-4-26T19:00:00Z
2022-4-26T20:00:00Z
2022-4-26T21:00:00Z
2022-4-26T22:00:00Z
2022-4-26T23:00:00Z
2022-4-25T01:00:00Z
2022-4-25T02:00:00Z
2022-4-25T03:00:00Z
2022-4-25T04:00:00Z
2022-4-25T05:00:00Z
2022-4-25T06:00:00Z
2022-4-25T07:00:00Z
2022-4-25T08:00:00Z
2022-4-25T09:00:00Z
2022-4-25T10:00:00Z
2022-4-25T11:00:00Z
2022-4-25T12:00:00Z
2022-4-25T13:00:00Z
2022-4-25T14:00:00Z
2022-4-25T15:00:00Z
2022-4-25T16:00:00Z
2022-4-25T17:00:00Z
2022-4-25T18:00:00Z
2022-4-25T19:00:00Z
2022-4-25T20:00:00Z
2022-4-25T21:00:00Z
2022-4-25T22:00:00Z
2022-4-25T23:00:00Z
2022-4-24T01:00:00Z
2022-4-24T02:00:00Z
2022-4-24T03:00:00Z
2022-4-24T04:00:00Z
2022-4-24T05:00:00Z
2022-4-24T06:00:00Z
2022-4-24T07:00:00Z
2022-4-24T08:00:00Z
2022-4-24T09:00:00Z
2022-4-24T10:00:00Z
2022-4-24T11:00:00Z
2022-4-24T12:00:00Z
2022-4-24T13:00:00Z
2022-4-24T14:00:00Z
2022-4-24T15:00:00Z
2022-4-24T16:00:00Z
2022-4-24T17:00:00Z
2022-4-24T18:00:00Z
2022-4-24T19:00:00Z
2022-4-24T20:00:00Z
2022-4-24T21:00:00Z
2022-4-24T22:00:00Z
2022-4-24T23:00:00Z

'Love Jesus Love truth Love my family Love our country. The Constitution must be protected.'

In [64]:
import re
result = []
user_dict = {}
# Loop through each response object
for response in tweets_array:
    # Take all of the users, and put them into a dictionary of dictionaries with the info we want to keep
    for user in response.includes['users']:
        user_dict[user.id] = {'username': user.username, 
                              'followers': user.public_metrics['followers_count'],
                              'tweets': user.public_metrics['tweet_count'],
                              'description': user.description,
                              'location': user.location
                             }
    for tweet in response.data:
        # For each tweet, find the author's information
        author_info = user_dict[tweet.author_id]
        # Put all of the information we want to keep in a single dictionary for each tweet
        result.append({'author_id': tweet.author_id, 
                       'username': author_info['username'],
                       'author_followers': author_info['followers'],
                       'author_tweets': author_info['tweets'],
                       'author_description': author_info['description'],
                       'author_location': author_info['location'],
                       'text': re.sub(r'[^A-Za-z0-9 ]+', '', tweet.text),
                       'created_at': tweet.created_at,
                       'retweets': tweet.public_metrics['retweet_count'],
                       'replies': tweet.public_metrics['reply_count'],
                       'likes': tweet.public_metrics['like_count'],
                       'quote_count': tweet.public_metrics['quote_count']
                      })

# Change this list of dictionaries into a dataframe
df = pd.DataFrame(result)

In [65]:
with pd.option_context('display.max_rows', 10, 'display.max_columns', None): 
    display(df)

,author_id,username,author_followers,author_tweets,author_description,author_location,text,created_at,retweets,replies,likes,quote_count
0,1248509877921726464,LydiaSteve6,41,4322,I am a Kenyan based web developer specializing...,None,onlinebusiness digitalmarketing makemoneyfast ...,2022-04-29 00:59:59+00:00,0,0,0,0
1,3198270209,JournalGAPE,390,218,The Journal of the Gilded Age and Progressive Era,None,BoydCothran one of the Journals editors was re...,2022-04-29 00:59:54+00:00,1,0,1,0
2,1518763019798552576,EaglesoverUSA,1,38,Love Jesus Love truth Love my family Love our ...,None,Charlie Kirk returns to Twitter Conservatives ...,2022-04-29 00:59:52+00:00,0,1,0,0
3,941466279470178304,gdlovgren,1939,14957,"Christian, Patriot, Conservative, Veteran, Def...",None,The Washington Posts Repulsive Defense Of Twit...,2022-04-29 00:59:49+00:00,0,0,0,0
4,13361922,stephencrose,196061,154084,85 year old Manhattan resident. Attended Exete...,"Manhattan, NY",MUSK blocked PUBLIC CITIZEN That does not mean...,2022-04-29 00:59:48+00:00,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
13727,41147623,ykhalim,33097,407359,I. I Obtained Unity in yoga on 7/20/80. 3 of m...,"Chicago, Lansing, Illinois",Twitter is reportedly reconsidering Elon Musks...,2022-04-24 22:50:05+00:00,0,0,0,0
13728,3135241,RedState,268825,144726,Unapologetic reporting and opinion by true con...,"Washington, D.C.",BREAKING WSJ Reports Twitter Will Reconsider E...,2022-04-24 22:50:01+00:00,36,2,139,2
13729,1136299562283331584,DorothyGrady7,84,45765,Memoirs of Blush by Dorothy Grady,None,Twitter is reportedly reconsidering Elon Musks...,2022-04-24 22:49:53+00:00,0,0,0,0
13730,700882040519053317,SylviaPage17,5,1179,Kingsdaughter ..,None,Say goodbyeElon Musks cryptic moving on tweet ...,2022-04-24 22:49:46+00:00,0,0,0,0
13731,24731611,mustang6944,142,16558,,"Henderson, NV",Twitter Meeting with Elon Musk to Discuss 43 B...,2022-04-24 22:49:46+00:00,0,0,0,0

In [66]:
df.to_csv('twitter_elonmusk_csv_test_full_clean.csv', encoding='utf-8', index=False)